stages:
  - test
  - compile
  - deploy


test:
  stage: test
  image: golang:latest
  script:
    - go test tests/helper_utils_test.go

build:
  stage: compile
  image: golang:latest
  script:
    - go mod init
    - go build

staging:
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=postit-api --api-key=$HEROKU_API_KEY
  environment:
    name: development
    url: https://postit-staging-api.herokuapp.com/
  only:
    - ci-cd